<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a18ece8e-fdd5-4f6d-8474-c6566edb3362</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DemoEnglish.Application\DemoEnglish.Application.csproj" />
    <ProjectReference Include="..\DemoEnglish.Infrastructure\DemoEnglish.Infrastructure.csproj" />
  </ItemGroup>

</Project>
